server:
  port: 81

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
      static-locations: classpath:/templates/,classpath:/static/,classpath:/public/

  #spring:
  application:
    name: consumer

  #用于分布式存储
  redis:
    port: 6379
    database: 0
    host: 47.93.221.88
    password: admin
    timeout: 60s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: consumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
