server:
  port: 6001

eureka:
  server:
    enable-self-preservation: false   #禁用保护
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost              #eureka服务端的实例名称(单机)
    #hostname: eureka6001.com          #eureka服务端的实例名称(集群)
  client:
    register-with-eureka: false       #false表示不向注册中心注册自己。
    fetch-registry: false             #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:6001/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。



